### ISSUE TITLE
Integer Global

### ISSUE THREAD

**Issue by ShaniRotemIl** [k2view-academy/K2View-Academy#1166]
Hi,

I created a new Global in the sharedGlobals, type Integer.
When trying to deploy, I'm getting the below error. Is there a limitation to work only with String Globals?

java.sql.SQLException: Deploy Customer Failed: Can not set static java.lang.Integer field com.k2view.cdbms.usercode.common.SharedGlobals.INT_GLOBAL to java.lang.String
        at com.k2view.fabric.common.Util.wrapCause(Util.java:186)
        at com.k2view.fabric.common.jdbc.JdbcUtil.sqlException(JdbcUtil.java:183)
        at com.k2view.fabric.session.sql.FabricStatement.doExecute(FabricStatement.java:244)
        at com.k2view.fabric.session.sql.FabricPreparedStatement.lambda$execute$1(FabricPreparedStatement.java:169)
        at com.k2view.fabric.common.jdbc.JdbcUtil.sqlException(JdbcUtil.java:181)
        at com.k2view.fabric.session.sql.FabricPreparedStatement.execute(FabricPreparedStatement.java:169)
        at com.k2view.fabric.common.jdbc.delegates.PreparedStatementDelegate.execute(PreparedStatementDelegate.java:216)
        at com.k2view.fabric.session.sql.SessionStatementWrapper$PrepareStatementDelegateWrapper.lambda$execute$0(SessionStatementWrapper.java:191)
        at com.k2view.fabric.session.sql.SessionStatementWrapper$StatementDelegateWrapper.postExecute(SessionStatementWrapper.java:105)
        at com.k2view.fabric.session.sql.SessionStatementWrapper$PrepareStatementDelegateWrapper.execute(SessionStatementWrapper.java:191)
        at com.k2view.fabric.session.managedbean.FabricCommandMB.statementExecute(FabricCommandMB.java:253)
        at com.k2view.fabric.session.managedbean.FabricCommandMB.executeCommand(FabricCommandMB.java:226)
        at com.k2view.fabric.session.managedbean.FabricCommandMB.executeUntilError(FabricCommandMB.java:215)
        at com.k2view.fabric.session.managedbean.FabricCommandMB.executeCommands(FabricCommandMB.java:209)
        at jdk.internal.reflect.GeneratedMethodAccessor738.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.k2view.fabric.api.endpoint.SimpleEndpoint.lambda$doInvoke$1(SimpleEndpoint.java:19)
        at com.k2view.fabric.common.Util.rte(Util.java:145)
        at com.k2view.fabric.api.endpoint.SimpleEndpoint.doInvoke(SimpleEndpoint.java:19)
        at com.k2view.fabric.api.endpoint.BaseEndpoint.invoke(BaseEndpoint.java:184)
        at com.k2view.fabric.api.ApiServlet.process(ApiServlet.java:162)
        at com.k2view.fabric.api.ApiServlet.doPost(ApiServlet.java:401)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:515)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
        at com.k2view.cdbms.ws.ErrorPageFilter.doFilter(ErrorPageFilter.java:56)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
        at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:307)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:934)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1690)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.k2view.fabric.session.common.FabricSessionException: Deploy Customer Failed: Can not set static java.lang.Integer field com.k2view.cdbms.usercode.common.SharedGlobals.INT_GLOBAL to java.lang.String
        at com.k2view.fabric.session.command.DeployCommand.coordinate(DeployCommand.java:139)
        at com.k2view.fabric.session.command.core.FabricDistributedCommand.doExecute(FabricDistributedCommand.java:30)
        at com.k2view.fabric.session.command.core.FabricCommand$BoundedFabricCommand.execute(FabricCommand.java:79)
        at com.k2view.fabric.session.sql.FabricStatement.lambda$doExecute$3(FabricStatement.java:247)
        at com.k2view.fabric.common.jdbc.JdbcUtil.sqlException(JdbcUtil.java:181)
        ... 48 common frames omitted
Caused by: java.lang.IllegalArgumentException: Can not set static java.lang.Integer field com.k2view.cdbms.usercode.common.SharedGlobals.INT_GLOBAL to java.lang.String
        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
        at java.base/jdk.internal.reflect.UnsafeStaticObjectFieldAccessorImpl.set(UnsafeStaticObjectFieldAccessorImpl.java:79)
        at java.base/java.lang.reflect.Field.set(Field.java:799)
        at com.k2view.cdbms.lut.LUType.tryReflectionOnPackage(LUType.java:2158)
        at com.k2view.cdbms.lut.LUType.changeGlobalValue(LUType.java:2076)
        at com.k2view.cdbms.lut.LUType.setLuClassLoader(LUType.java:950)
        at com.k2view.cdbms.lut.LUType.init(LUType.java:693)
        at com.k2view.cdbms.lut.LUType.create(LUType.java:538)
        at com.k2view.cdbms.lut.LUType.create(LUType.java:472)
        at com.k2view.fabric.session.command.DeployCommand.coordinatorDeployLutype(DeployCommand.java:387)
        at com.k2view.fabric.session.command.DeployCommand.coordinate(DeployCommand.java:132)
        ... 52 common frames omitted

**Comment by taliei** [comment]
Hi.

A Global must be a String. Fabric does not support Integer type Globals.

Tali

**Comment by ShaniRotemIl** [comment]
Thanks
