### ISSUE TITLE
Cassandra docker images with fabric docker

### ISSUE THREAD

**Issue by sathishpuram** [k2view-academy/K2View-Academy#152]
When we load the cassandra docker image and fabric images, and try to start the fabric server,  Fabric server fails with below exception:

ERROR 2020-12-10 16:38:41,776 [LID6666000000000001] [main] c.k.f.b.Boot -
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /172.25.0.116:9042 (com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency LOCAL_QUORUM (1 required but only
 0 alive)))
        at com.datastax.driver.core.exceptions.NoHostAvailableException.copy(NoHostAvailableException.java:83)
        at com.datastax.driver.core.exceptions.NoHostAvailableException.copy(NoHostAvailableException.java:37)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
        at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:293)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:58)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:45)
        at com.k2view.cdbms.dao.MasterKeyDao.execute(MasterKeyDao.java:40)
        at com.k2view.cdbms.dao.MasterKeyDao.getAllKeysDescriptions(MasterKeyDao.java:107)
        at com.k2view.cdbms.keys.MasterKeyDescription.fetchAll(MasterKeyDescription.java:24)
        at com.k2view.cdbms.keys.MasterKeyManager.reloadPhase1(MasterKeyManager.java:60)
        at com.k2view.cdbms.keys.MasterKeyManager.reloadPhase1(MasterKeyManager.java:48)
        at com.k2view.cdbms.keys.MasterKeyManager.reload(MasterKeyManager.java:89)
        at com.k2view.cdbms.boot.FabricEncryptionSystem.createDefaultMasterkey(FabricEncryptionSystem.java:70)
        at com.k2view.cdbms.boot.FabricEncryptionSystem.start(FabricEncryptionSystem.java:40)
        at com.k2view.fabric.boot.BootContext.start(BootContext.java:89)
        at com.k2view.fabric.boot.BootContext.start(BootContext.java:72)
        at com.k2view.fabric.boot.BootContext.start(BootContext.java:57)
        at com.k2view.fabric.boot.Boot.start(Boot.java:70)
        at com.k2view.fabric.boot.Boot.main(Boot.java:104)

**Comment by sathishpuram** [comment]
The root cause is that k2view keyspaces' in the docker images are setup with replication strategy as "NetworkTopologyStrategy". This doesn't work with single instance of cassandra node. We have update the replication strategy for all the k2view keyspaces to "SimpleStrategy".

https://stackoverflow.com/questions/39904798/error-during-inserting-data-nohostavailable
