### ISSUE TITLE
java.sql.SQLException Password was encrypted with unknown master key

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#205]
I'm doing some development on Fabric 6.4.2_47 running on Linux.
On Studio, environment `DEV_RE21` is set as debug (Tools>User Preferences>Server Configuration>Debug Env.).
On Server, environment is set as `DEV_RE21`, instead of `_dev`.

At certain moment, I wanted to clean DEV_RE21 so I could redeploy and test all again from scratch.
I stopped Fabric and reset it.

```bash
k2view@ip-10-70-0-58:~ . fabric/scripts/reset.sh DROP_ALL
/opt/apps/k2view/fabric/scripts/force-stop.sh: line 7: kill: (29423) - No such process
Using config: /opt/apps/k2view/config/config.ini
Using mode: DROP_ALL
Using black list:
cluster id was not defined
Deleting dir /opt/apps/k2view/storage/common
Deleting dir /dev/shm/fdb_cache
Deleting dir /opt/apps/k2view/storage
Deleting keyspace k2view_vkd
Deleting keyspace k2batchprocess
Deleting keyspace k2system
Deleting keyspace k2auth
Deleting keyspace k2view_iidf_lu
Deleting keyspace k2audit
Deleting keyspace system_auth
Cannot DROP <keyspace system_auth>
Deleting keyspace k2staging
Deleting keyspace system_traces
Cannot DROP <keyspace system_traces>
Deleting keyspace system
system keyspace is not user-modifiable.
Deleting keyspace system_distributed
Cannot DROP <keyspace system_distributed>
Deleting keyspace k2_commons
Deleting keyspace system_schema
system_schema keyspace is not user-modifiable.
Deleting keyspace k2view_k2automation
Deleting kafka topics: Search_DEV_RE21,Delta_cluster_VKD,Search,CDC_TOPIC,CDC_TOPIC_DEV_RE21,common_area_PROCESS,common_area_IIDF_STATISTICS
```

Before restarting Fabric, I recreated `storage/conf/node.id`, now with `uuid:DEV21` and `cluster_id:DEV21`.
Previously, `uuid` was set with an auto generated UUID and `cluster_id` was empty.

I started Fabric and redeployed code.
But when I try to deploy environment `DEV_RE21` it complains with  

```
...
ERROR 2021-04-03 15:35:35,442 [LIDea3a000000000006] [http-nio-3213-exec-1] c.k.f.s.c.DeployEnvironmentsCommand - Failed to encrypt password in the deployed file!
java.lang.RuntimeException: Password was encrypted with unknown master key (keyId: 1616416506294)
...
ERROR 2021-04-03 15:35:35,445 [LIDea3a000000000006] [http-nio-3213-exec-1] c.k.c.w.DeployEnvironmentsToCdbmsServlet - Deployment environments has failed . Failure reason:
java.sql.SQLException: Password was encrypted with unknown master key (keyId: 1616416506294)
...
Caused by: java.lang.RuntimeException: Password was encrypted with unknown master key (keyId: 1616416506294)
        at com.k2view.cdbms.FabricEncryption.MasterKeyEncryptionProvider.decrypt(MasterKeyEncryptionProvider.java:51)
        at com.k2view.cdbms.FabricEncryption.MasterKeyEncryptionProvider.decrypt(MasterKeyEncryptionProvider.java:33)
        at com.k2view.fabric.common.encryption.Encryption.decrypt(Encryption.java:61)
        at com.k2view.cdbms.FabricEncryption.FabricEncryption.decrypt(FabricEncryption.java:12)
        at com.k2view.fabric.session.command.DeployEnvironmentsCommand.encryptPasswordsInXml(DeployEnvironmentsCommand.java:119)
        at com.k2view.fabric.session.command.DeployEnvironmentsCommand.coordinate(DeployEnvironmentsCommand.java:64)
        at com.k2view.fabric.session.command.core.FabricDistributedCommand.doExecute(FabricDistributedCommand.java:30)
        at com.k2view.fabric.session.command.core.FabricCommand$BoundedFabricCommand.execute(FabricCommand.java:63)
        at com.k2view.fabric.session.sql.FabricStatement.lambda$doExecute$0(FabricStatement.java:76)
        at com.k2view.fabric.common.jdbc.JdbcUtil.sqlException(JdbcUtil.java:161)
        ... 34 common frames omitted
```

I stopped Fabric, reset it again and this time didn't edit `node.id` letting it be auto generated, but error persisted.

So, what am I missing in this process?

**Comment by feamcor** [comment]
Ok, I found the issue.
I retyped all passwords of environment DEV_RE21, allowing Studio to re-encrypt them.
I recommend to add this remark somewhere in the academy wiki.
Also, I recommend product to improve the error message, guiding user to proper resolution.
Cheers.

**Comment by natalylic** [comment]
Thanks Fabio, a note was added to the article:
https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.2/articles/25_environments/02_create_new_environment.md
Will be updated in the web site after the build.
