### ISSUE TITLE
DbLoad Incomplete SQL Statement

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#746]
Fabric 6.5.2

Actor `DbLoad`, `command` is `upsert`, `IgnoreNulls` is `true`.

Target table has only two columns to map, one is the PK and will always be available, but the second one, in some scenarios, is not available (i.e. `null`) and then the actor fails (see exception below) because the actor doesn't compose the full SQL statement.

In such case, shouldn't the actor (maybe) not emit any command?

Please advise.
Thanks.

```java
INSERT INTO PREPAID.PARTY (PARTYID) VALUES (?) ON CONFLICT(PARTYID) DO UPDATE SET  class com.k2view.fabric.parser.parser.ParseException Cause: Encountered " "ON" "ON "" at line 1, colum
n 48.
Was expecting one of:
    <EOF>
    ";" ...
        at com.k2view.broadway.actors.builtin.DbCommand.execute(DbCommand.java:103)
        at com.k2view.broadway.actors.builtin.DbCommand.action(DbCommand.java:71)
        at com.k2view.broadway.actors.builtin.DbAbstractSql.action(DbAbstractSql.java:41)
        at com.k2view.broadway.model.Actor.action(Actor.java:71)
        at com.k2view.broadway.model.ActorWrapper.act(ActorWrapper.java:197)
        at com.k2view.broadway.model.StageImp.lambda$runActor$5(StageImp.java:299)
        at com.k2view.broadway.trace.TraceReport.actor(TraceReport.java:112)
        at com.k2view.broadway.model.StageImp.runActor(StageImp.java:298)
        at com.k2view.broadway.model.StageImp.tryRunningActor(StageImp.java:288)
        at com.k2view.broadway.model.StageImp.lambda$action$2(StageImp.java:215)
        at com.k2view.broadway.trace.TraceReport.stage(TraceReport.java:85)
        at com.k2view.broadway.model.StageImp.action(StageImp.java:181)
        at com.k2view.broadway.model.FlowImp.runStage(FlowImp.java:516)
        at com.k2view.broadway.model.FlowImp.runLevelStages(FlowImp.java:472)
        at com.k2view.broadway.model.FlowImp.runLevel(FlowImp.java:359)
        at com.k2view.broadway.model.FlowImp.runFlow(FlowImp.java:306)
        at com.k2view.broadway.model.FlowImp.act(FlowImp.java:232)
        at com.k2view.broadway.model.FlowImp.act(FlowImp.java:965)
        at com.k2view.broadway.model.FlowImp.lambda$act$18(FlowImp.java:947)
        at com.k2view.broadway.trace.TraceReport.flow(TraceReport.java:56)
        at com.k2view.broadway.model.FlowImp.act(FlowImp.java:942)
        at com.k2view.broadway.model.FlowImp.act(FlowImp.java:932)
        at com.k2view.broadway.BroadwayImpPool$PooledFlow.lambda$act$1(BroadwayImpPool.java:72)
        at com.k2view.broadway.BroadwayImpPool$PooledFlow.actAndReturn(BroadwayImpPool.java:82)
        at com.k2view.broadway.BroadwayImpPool$PooledFlow.act(BroadwayImpPool.java:72)
        at com.k2view.broadway.actors.builtin.InnerFlow.action(InnerFlow.java:19)
        at com.k2view.broadway.model.Actor.action(Actor.java:71)
        at com.k2view.broadway.model.ActorWrapper.act(ActorWrapper.java:197)
        at com.k2view.broadway.model.StageImp.lambda$runActor$5(StageImp.java:299)
        at com.k2view.broadway.trace.TraceReport.actor(TraceReport.java:112)
        at com.k2view.broadway.model.StageImp.runActor(StageImp.java:298)
        ... 85 common frames omitted
```

**Comment by natalylic** [comment]
This behavior is changed in 7.0 and it depends on the source DB, e.g. in SQLite it will do nothing, in ORACLE - throw an exception.

**Comment by natalylic** [comment]
In your Fabric version, don't set IgnoreNulls to true to prevent the exception.
