### ISSUE TITLE
Decode gzip SOAP response in BW

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#869]
Hello, is there a way to decode SOAP response that is coming in gzip format using BW flow? 

XmlParser gives us below error:

`java.sql.SQLException: Flow: TestAPIHTTP Level: 3 Stage: Stage 3 Actor: XmlParser1 Unexpected character '�' (code 65533 / 0xfffd) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,2] class com.ctc.wstx.exc.WstxUnexpectedCharException Cause: Unexpected character '�' (code 65533 / 0xfffd) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,2]
    at com.k2view.fabric.common.Util.wrapCause(Util.java:185)
    at com.k2view.fabric.common.jdbc.JdbcUtil.sqlException(JdbcUtil.java:183)
    at com.k2view.fabric.session.sql.FabricStatement.doExecute(FabricStatement.java:244)
    at com.k2view.fabric.session.sql.FabricPreparedStatement.lambda$execute$1(FabricPreparedStatement.java:169)
`

<img width="355" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/394a05eb-485d-4ad5-8930-2a96f508a197">

_____________
Best regards,
         Andrey

**Comment by natalylic** [comment]
There is an **Uncompress** actor - to read compressed data from a stream, un-compress it and return a stream with the uncompressed data.

**Comment by avvakandr** [comment]
Hi Nataly - yes, that worked! thank you!

_____________
Best regards,
          Andrey
