### ISSUE TITLE
How to use a trigger function to query the LUI being updated?

### ISSUE THREAD

**Issue by benkipnis** [k2view-academy/K2View-Academy#99]
I have a trigger function.  I want to use the newValues() and augment with existing data in other LUI tables.

When i try to query via fabric() or ludb() i receive errors.

How can i query the LUDB from within a trigger function?

**Comment by lionbro1** [comment]
Hi,

ludb() or fabric() should work, can you share the code and the error message you are getting?

**Comment by danicar12** [comment]
No error but also no update inside the LUI.
Similar code with insert command instead update command works properly. Looks like a problem with “update” command on LUI?

Best regards,

Daniel Carrera Alonso
Technical Account Manager
K2VIEW
daniel.carrera.alonso@k2view.com
m. +31 (0) 629395413
whatsapp. +48 694443243

**Comment by lionbro1** [comment]
Daniel,

I suspect you comment on other issue.

Ben mentioned, When i try to query via fabric() or ludb() i receive errors.

So i asked what is the error? he opened a separate issue on the UPDATE statement that i replied as well.

Regards,
Lion

**Comment by danicar12** [comment]
Ohh yes! Sorry about it. I related to the other one.

Best regards,

Daniel Carrera Alonso
Technical Account Manager
K2VIEW
daniel.carrera.alonso@k2view.com
m. +31 (0) 629395413
whatsapp. +48 694443243

**Comment by benkipnis** [comment]
Error Text:

ERROR [http-nio-3214-exec-2] 2020-09-29 22:32:52,974 c.k.f.a.ApiServlet - [LIDa00000000004a] Failed while executing updateResponderLocation
com.k2view.fabric.api.ApiServletException: com.k2view.cdbms.exceptions.SyncException: Exception in updateResponderLocation(): org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (java.sql.SQLException: com.k2view.cdbms.exceptions.UnsupportedInterfaceException: SYNC service type is not supported for this execution)
	at com.k2view.fabric.api.endpoint.BaseEndpoint.lambda$invoke$19(BaseEndpoint.java:135)
	at com.k2view.fabric.common.Util.wrapCause(Util.java:151)
	at com.k2view.fabric.api.endpoint.BaseEndpoint.invoke(BaseEndpoint.java:135)
	at com.k2view.fabric.api.ApiServlet.process(ApiServlet.java:109)
	at com.k2view.fabric.api.ApiServlet.doGet(ApiServlet.java:232)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.k2view.cdbms.ws.ErrorPageFilter.doFilter(ErrorPageFilter.java:56)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:305)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.k2view.cdbms.exceptions.SyncException: Exception in updateResponderLocation(): org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (java.sql.SQLException: com.k2view.cdbms.exceptions.UnsupportedInterfaceException: SYNC service type is not supported for this execution)
	at com.k2view.cdbms.lut.FunctionDef.invoke(FunctionDef.java:187)
	at com.k2view.cdbms.lut.FunctionDef.invokeFromMap(FunctionDef.java:149)
	at com.k2view.cdbms.lut.FunctionDef.invokeFromMap(FunctionDef.java:138)
	at com.k2view.cdbms.ws.ManagedWebExecution.process(ManagedWebExecution.java:31)
	at com.k2view.cdbms.ws.ManagedWebExecution.execute(ManagedWebExecution.java:26)
	at com.k2view.cdbms.ws.WebServiceMB.lambda$invoke$272(WebServiceMB.java:74)
	at com.k2view.fabric.common.Util.rte(Util.java:132)
	at com.k2view.cdbms.ws.WebServiceMB.invoke(WebServiceMB.java:74)
	at com.k2view.cdbms.ws.WebServiceMB$WebServiceEndpoint.doInvoke(WebServiceMB.java:149)
	at com.k2view.fabric.api.endpoint.BaseEndpoint.invoke(BaseEndpoint.java:129)
	... 26 common frames omitted
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (java.sql.SQLException: com.k2view.cdbms.exceptions.UnsupportedInterfaceException: SYNC service type is not supported for this execution)
	at org.sqlite.core.DB.newSQLException(DB.java:941)
	at org.sqlite.core.DB.newSQLException(DB.java:953)
	at org.sqlite.core.DB.execute(DB.java:857)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:56)
	at com.k2view.fabric.common.jdbc.delegates.PreparedStatementDelegate.execute(PreparedStatementDelegate.java:216)
	at com.k2view.fabric.fabricdb.context.PreparedStatementCache$CachedPreparedStatements.execute(PreparedStatementCache.java:93)
	at com.k2view.fabric.common.jdbc.delegates.PreparedStatementDelegate.execute(PreparedStatementDelegate.java:216)
	at com.k2view.fabric.session.sql.FabricTransaction$SORPreparedStatement.execute(FabricTransaction.java:233)
	at com.k2view.fabric.common.jdbc.delegates.PreparedStatementDelegate.execute(PreparedStatementDelegate.java:216)
	at com.k2view.fabric.common.jdbc.delegates.PreparedStatementDelegate.execute(PreparedStatementDelegate.java:216)
	at com.k2view.fabric.session.sql.SessionStatementWrapper$PrepareStatementDelegateWrapper.lambda$execute$16(SessionStatementWrapper.java:185)
	at com.k2view.fabric.session.sql.SessionStatementWrapper$StatementDelegateWrapper.postExecute(SessionStatementWrapper.java:105)
	at com.k2view.fabric.session.sql.SessionStatementWrapper$PrepareStatementDelegateWrapper.execute(SessionStatementWrapper.java:185)
	at com.k2view.fabric.common.jdbc.delegates.PreparedStatementDelegate.execute(PreparedStatementDelegate.java:216)
	at com.k2view.cdbms.shared.Db$PreparedStatement.execute(Db.java:345)
	at com.k2view.cdbms.shared.Db.execute(Db.java:189)
	at com.k2view.cdbms.usercode.lu.k2_ws.RESPONDER.Logic.updateResponderLocation(Logic.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.k2view.cdbms.lut.FunctionDef.invoke(FunctionDef.java:201)
	at com.k2view.cdbms.lut.FunctionDef.invoke(FunctionDef.java:171)
	... 35 common frames omitted

**Comment by benkipnis** [comment]
i've tried a few methods include ludb() and creating a new connection (Db conn = db("fabric")).

**Comment by lionbro1** [comment]
please share the trigger function code

**Comment by benkipnis** [comment]
I have gone through several versions of code (trying ludb() & fabric() in addition to the Db connection below) and all provide similar errors.


String tbl = tableDataChange.getTable().toString();
DataChangeType change = tableDataChange.getType();
String queryUserDataSql = "SELECT username, account_type, ctn, fan, first_name, last_name, groups, org_name, sub_type FROM users";
String updateCurrentLocationSql = "UPDATE location SET username=?, account_type=?, ctn=?, fan=?, first_name=?, last_name=?, groups=?, org_name=?, sub_type=?, location_ts=?, latitude=?, longitude=? WHERE username=? AND ctn=?";

if (change == DataChangeType.INSERT)
{
	Map<String, Object> newValues = tableDataChange.newValues();
	
	Db conn = db("fabric");
	conn.execute("get RESPONDER.?", k2_getInstanceID());
	Db.Row userData = conn.fetch(queryUserDataSql).firstRow();

	//Db conn = db("POSTGRES");
	//conn.execute(updateCurrentLocationSql, userData.get("username"), userData.get("account_type"), userData.get("ctn"), userData.get("fan"), userData.get("first_name"),
	//										userData.get("last_name"), userData.get("groups"), userData.get("org_name"), userData.get("sub_type"), newValues.get("location_ts"),
	//										newValues.get("latitude"), newValues.get("longitude"), userData.get("username"), userData.get("ctn"));

	log.info("INSIDE TRIGGER - " + newValues.get("LONGITUDE"));

	//ludb().beginTransaction();
	//ludb().execute(updateCurrentLocationSql, userData.get("username"), userData.get("account_type"), userData.get("ctn"), userData.get("fan"), userData.get("first_name"),
	//										userData.get("username"), userData.get("username"), userData.get("username"), userData.get("username"), newValues.get("location_ts"),
	//										newValues.get("latitude"), newValues.get("longitude"), userData.get("username"), userData.get("ctn"));
	//ludb().commit();
}

**Comment by lionbro1** [comment]
The line with k2_getInstanceID() should be replaced by conn.fetch("select iid(schenmaname)").firstRow()

There was already an issue documented on it  

https://github.com/k2view-academy/K2View-Academy/issues/92

**Comment by benkipnis** [comment]
I've updated the line in question and now i get an error about a trigger existing.  See code and error below.

CODE:
```
String tbl = tableDataChange.getTable().toString();
DataChangeType change = tableDataChange.getType();
String queryUserDataSql = "SELECT username, account_type, ctn, fan, first_name, last_name, groups, org_name, sub_type FROM users";
String updateCurrentLocationSql = "UPDATE location_history SET username=?, account_type=?, ctn=?, fan=?, first_name=?, last_name=?, groups=?, org_name=?, sub_type=?, location_ts=?, latitude=?, longitude=? WHERE username=? AND ctn=?";

if (change == DataChangeType.INSERT)
{
	Map<String, Object> newValues = tableDataChange.newValues();
	
	Db conn = db("fabric");
	Db.Row iid = conn.fetch("select iid('RESPONDER')").firstRow();
	conn.execute("get RESPONDER.?", iid.get(0));
	Db.Row userData = conn.fetch(queryUserDataSql).firstRow();

	log.info("INSIDE TRIGGER - " + newValues.get("LONGITUDE"));
}
```


ERROR:
```
ERROR [http-nio-3213-exec-1] 2020-09-30 18:49:47,488 c.k.f.a.ApiServlet - [LIDd6000000000018] Failed while executing updateResponderLocation
com.k2view.fabric.api.ApiServletException: com.k2view.cdbms.exceptions.SyncException: Exception in updateResponderLocation(): org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (java.sql.SQLException: com.k2view.cdbms.exceptions.SyncException: Exception in updateCurrentLocation(): java.sql.SQLException: Triggers exists for schema RESPONDER)
	at com.k2view.fabric.api.endpoint.BaseEndpoint.lambda$invoke$19(BaseEndpoint.java:135)
	at com.k2view.fabric.common.Util.wrapCause(Util.java:151)
	at com.k2view.fabric.api.endpoint.BaseEndpoint.invoke(BaseEndpoint.java:135)
	at com.k2view.fabric.api.ApiServlet.process(ApiServlet.java:109)
	at com.k2view.fabric.api.ApiServlet.doGet(ApiServlet.java:232)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.k2view.cdbms.ws.ErrorPageFilter.doFilter(ErrorPageFilter.java:56)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:305)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.k2view.cdbms.exceptions.SyncException: Exception in updateResponderLocation(): org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (java.sql.SQLException: com.k2view.cdbms.exceptions.SyncException: Exception in updateCurrentLocation(): java.sql.SQLException: Triggers exists for schema RESPONDER)
	at com.k2view.cdbms.lut.FunctionDef.invoke(FunctionDef.java:187)
	at com.k2view.cdbms.lut.FunctionDef.invokeFromMap(FunctionDef.java:149)
	at com.k2view.cdbms.lut.FunctionDef.invokeFromMap(FunctionDef.java:138)
	at com.k2view.cdbms.ws.ManagedWebExecution.process(ManagedWebExecution.java:31)
	at com.k2view.cdbms.ws.ManagedWebExecution.execute(ManagedWebExecution.java:26)
	at com.k2view.cdbms.ws.WebServiceMB.lambda$invoke$272(WebServiceMB.java:74)
	at com.k2view.fabric.common.Util.rte(Util.java:132)
	at com.k2view.cdbms.ws.WebServiceMB.invoke(WebServiceMB.java:74)
	at com.k2view.cdbms.ws.WebServiceMB$WebServiceEndpoint.doInvoke(WebServiceMB.java:149)
	at com.k2view.fabric.api.endpoint.BaseEndpoint.invoke(BaseEndpoint.java:129)
	... 26 common frames omitted
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (java.sql.SQLException: com.k2view.cdbms.exceptions.SyncException: Exception in updateCurrentLocation(): java.sql.SQLException: Triggers exists for schema RESPONDER)
	at org.sqlite.core.DB.newSQLException(DB.java:941)
	at org.sqlite.core.DB.newSQLException(DB.java:953)
	at org.sqlite.core.DB.execute(DB.java:857)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:56)
	at com.k2view.fabric.common.jdbc.delegates.PreparedStatementDelegate.execute(PreparedStatementDelegate.java:216)
	at com.k2view.fabric.fabricdb.context.PreparedStatementCache$CachedPreparedStatements.execute(PreparedStatementCache.java:93)
	at com.k2view.fabric.common.jdbc.delegates.PreparedStatementDelegate.execute(PreparedStatementDelegate.java:216)
	at com.k2view.fabric.session.sql.FabricTransaction$SORPreparedStatement.execute(FabricTransaction.java:233)
	at com.k2view.fabric.common.jdbc.delegates.PreparedStatementDelegate.execute(PreparedStatementDelegate.java:216)
	at com.k2view.fabric.common.jdbc.delegates.PreparedStatementDelegate.execute(PreparedStatementDelegate.java:216)
	at com.k2view.fabric.session.sql.SessionStatementWrapper$PrepareStatementDelegateWrapper.lambda$execute$16(SessionStatementWrapper.java:185)
	at com.k2view.fabric.session.sql.SessionStatementWrapper$StatementDelegateWrapper.postExecute(SessionStatementWrapper.java:105)
	at com.k2view.fabric.session.sql.SessionStatementWrapper$PrepareStatementDelegateWrapper.execute(SessionStatementWrapper.java:185)
	at com.k2view.fabric.common.jdbc.delegates.PreparedStatementDelegate.execute(PreparedStatementDelegate.java:216)
	at com.k2view.cdbms.shared.Db$PreparedStatement.execute(Db.java:345)
	at com.k2view.cdbms.shared.Db.execute(Db.java:189)
	at com.k2view.cdbms.usercode.lu.k2_ws.RESPONDER.Logic.updateResponderLocation(Logic.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.k2view.cdbms.lut.FunctionDef.invoke(FunctionDef.java:201)
	at com.k2view.cdbms.lut.FunctionDef.invoke(FunctionDef.java:171)
	... 35 common frames omitted

```

**Comment by benkipnis** [comment]
Issue was with the field named "groups".  Once this was removed things worked fine.
